# Funding options for SmartClone Core
# Replace these with your actual funding platforms

# GitHub Sponsors
github: # [yourusername]

# Open Collective
# open_collective: smartclone-core

# Patreon
# patreon: smartclone

# Custom sponsorship links
# custom: ['https://your-website.com/donate', 'https://buy-me-a-coffee.com/yourusername']
